// <auto-generated />
namespace n01629153_Event_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatecheck : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecheck));
        
        string IMigrationMetadata.Id
        {
            get { return "202402052252401_updatecheck"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
